eistiens_net_v3/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from accounts import views


urlpatterns = [
    url(r'^login$',  views.login,                     name='login'),
    url(r'^logout$', logout,      {'next_page': '/'}, name='logout'),
]

eistiens_net_v3/associations/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^(?P<id>\d+)$', views.details, name='details'),
    url(r'^(?P<id>\d+)/edit$', views.edit, name='edit'),
    url(r'^join/(?P<id>\d+)$', views.join, name='join'),
]

eistiens_net_v3/eistiens_net_v3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from . import settings
from portal import views as portal_views


urlpatterns = [
    url(r'^$',          portal_views.home_page, name='portal'),
    url(r'^admin/',     admin.site.urls),
    url(r'^accounts/',  include('accounts.urls', namespace='accounts')),
    url(r'^associations/',
        include('associations.urls', namespace='associations')
        ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

eistiens_net_v3/associations/models.py
from django.db import models

from accounts.models import Account
from common.models import SchoolYear


class Association(models.Model):
    VALIDATION_STATES = (
        ('MD', 'Missing documents'),
        ('SM', 'Submittable'),
        ('PE', 'Pending'),
        ('AC', 'Accepted'),
        ('RF', 'Refused'),
    )

    name = models.CharField(
        "Nom de l'association",
        max_length=60,
    )

    description = models.TextField(
        "Description de l'association",
        default="",
        blank=True,
    )

    validation_state = models.CharField(
        "État de la validation",
        default='MD',
        max_length=2,
        choices=VALIDATION_STATES,
    )

    logo = models.ImageField(
        "Logo de l'association",
        upload_to="associations/logo",
        default="associations/logo/default.png"
    )

    banner = models.ImageField(
        "Bannière de l'association",
        upload_to="associations/banner",
        default="associations/banner/default.png"
    )

    subscription_cost = models.DecimalField(
        "Coût de la cotisation",
        max_digits=5,
        decimal_places=2,
        default=0,
    )

    room = models.CharField(
        "Local de l'association",
        max_length=5,
        default="",
        blank=True,
    )

    members = models.ManyToManyField(
        Account,
        through='Membership',
        through_fields=('association', 'account')
    )

    def __str__(self):
        return self.name

    def is_member(self, user):
        if user.is_authenticated():
            a = Account.objects.get(user=user)
            s = SchoolYear.objects.last()
            return self.membership_set.filter(account=a, year=s).exists()
        return False


class Membership(models.Model):
    """
    Model to represent a membership entry. It is linked to a year, meaning we
    can keep data on members from previous years.
    A member can be member of executive board, with a role, either defined
    on the DEFAULT_ROLES entry, or something else (OT), in which case the
    custom_role is filed.
    Any member cas also setup a custom role, which does not imply he's member
    of the executive board.
    By default, a member is not flagged as accepted, and it's up the the
    executive board's members to accept him.
    """
    DEFAULT_ROLES = (
        ('PR', 'Président'),
        ('VP', 'Vice-Président'),
        ('TR', 'Trésorier'),
        ('RC', 'Responsable communications'),
        ('SC', 'Secrétaire'),
        ('OT', 'Autre'),
    )

    date_subscription = models.DateField(auto_now_add=True)

    is_board = models.BooleanField(default=False)

    role = models.CharField(max_length=2, choices=DEFAULT_ROLES)

    custom_role = models.CharField(max_length=30, default="", blank=True)

    accepted = models.BooleanField(default=False)

    year = models.ForeignKey(SchoolYear, on_delete=models.CASCADE)

    association = models.ForeignKey(Association, on_delete=models.CASCADE)

    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    def __str__(self):
        return self.account.__str__() + ' - ' + self.association.__str__()


class SocialLink(models.Model):
    PRESETS = (
        ('FB', 'Facebook'),
        ('TW', 'Twitter'),
        ('YT', 'YouTube'),
        ('WE', 'Site internet'),
        ('MA', 'Mail'),
        ('OT', 'Autre'),
    )

    association = models.ForeignKey(Association, on_delete=models.CASCADE)

    type_link = models.CharField(max_length=2, choices=PRESETS)

    url = models.URLField()

    def __str__(self):
        return '[' + self.association.__str__() + '] ' + self.url


class Refusal(models.Model):
    """
    Object representing a comment from EISTI's administration to explain
    why an association was refused.
    """
    text = models.TextField(
        "Commentaires sur le refus",
        default="",
        blank=True,
    )

    association = models.ForeignKey(Association, on_delete=models.CASCADE)

    comment_date = models.DateTimeField(
        "Date du commentaire",
        auto_now=True,
    )

    def __str__(self):
        return self.association.__str__()


class Document(models.Model):
    Statuses = models.FileField(
        "Status de l'association",
        upload_to='admin_doc/%Y/',
    )

    internal_regulations = models.FileField(
        "Règlement intérieur",
        upload_to='admin_doc/%Y/',
    )

    banking_account_info = models.FileField(
        "RIB",
        upload_to='admin_doc/%Y/',
    )

    insurance = models.FileField(
        "Assurances",
        upload_to='admin_doc/%Y/',
    )

    association = models.ForeignKey(Association, on_delete=models.CASCADE)

    year = models.ForeignKey(SchoolYear, on_delete=models.CASCADE)

    def __str__(self):
        return '[' + self.year.__str__() + '] ' + self.association.__str__()

eistiens_net_v3/associations/forms.py
from django import forms

from .models import Association


class AssociationForm(forms.ModelForm):
    class Meta:
        model = Association
        fields = ['description', 'subscription_cost', 'logo', 'banner', 'room']

eistiens_net_v3/associations/views.py
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.utils import IntegrityError
from django.shortcuts import (
    get_object_or_404,
    HttpResponseRedirect,
    redirect,
    render)

from common.models import SchoolYear
from .models import Account, Association, Membership
from .forms import AssociationForm


def orderKey(links):
    L = ['FB', 'TW', 'YT', 'WE', 'MA', 'OT']
    return (L.index(links.type_link))


def list(request):
    assos = {
        (asso, asso.is_member(request.user))
        for asso in Association.objects.all()
    }

    return render(
        request,
        'associations/list.html',
        {'assos': assos}
    )


def details(request, id):
    asso = get_object_or_404(Association, pk=id)
    links = sorted(asso.sociallink_set.all(), key=orderKey)
    is_member = asso.is_member(request.user)

    return render(
        request,
        'associations/details.html',
        {'asso': asso, 'links': links, 'is_member': is_member}
    )


# TODO: It will be necessary to check who the authenticated user is
@login_required
def join(request, id):
    asso = get_object_or_404(Association, pk=id)
    # No need to check if the account exists
    account = Account.objects.get(user=request.user)

    try:
        Membership.objects.create(
            account=account,
            role='OT',
            year=SchoolYear.objects.last(),
            association=asso
        )
    except IntegrityError:
        messages.error(request, "Une erreur s'est produite!")

    messages.success(request,
                     "Votre inscription est en attente de validation par le " +
                     "bureau de l'association {}".format(asso.name))
    return redirect(
            reverse('associations:details', kwargs={'id': asso.pk}))


def edit(request, id):
    asso = get_object_or_404(Association, pk=id)

    if request.method == 'POST':
        form = AssociationForm(request.POST, instance=asso)
        if form.is_valid():
            form.save()
            url = reverse('associations:details', kwargs={'id': id})
            return HttpResponseRedirect(url)
        else:
            messages.error(request, 'Il y a des erreur dans le formulaire')

    form = AssociationForm(instance=asso)

    return render(
        request,
        'associations/edit.html',
        {'form': form, 'name': asso.name, 'pk': id})

eistiens_net_v3/associations/templates/associations/details.html
{% extends 'common/base.html' %}

{% load static from staticfiles %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static "css/associations.css" %}"/>
{% endblock %}

{% block title %}{{ asso.name  }} {{ super }}{% endblock %}

{% block content %}
    <div id="banner" style="background-image: url('{{ asso.banner.url }}');">
        <div class="logo-wrapper" >
            <img class="logo responsive-img" src="{{ asso.logo.url }}"/>
        </div>
    </div>
    <div class="container">
        <h3 id="name-asso">{{ asso.name }}</h3>
        <hr style="width:80%; margin-bottom: 20px"/>
        <div id="info-asso-grid">
            <div id="info-column">
                <div id="info-title">
                    <h5>Informations pratique</h5>
                </div>
                <div id="info-description">
                    <p>Local : {{ asso.room }}</p>

                    {% if asso.subscription_cost > 0 %}
                        <p>Cotisation : {{ asso.subscription_cost }}€</p>
                    {% else %}
                        <p>Inscription gratuite</p>
                    {% endif %}
                    {% if links %}
                        <div id="social-links">
                            {% for link in links %}
                                {% if link.type_link == "FB" %}
                                    <a class="sn-link fb" href={{ link.url }} target=_blank>
                                        <i class="fab fa-facebook-f fa-2x"></i>
                                    </a>
                                {% elif link.type_link == "TW" %}
                                    <a class="sn-link tw" href={{ link.url }} target=_blank>
                                        <i class="fab fa-twitter fa-2x"></i>
                                    </a>
                                {% elif "YT" == link.type_link %}
                                    <a class="sn-link yt" href={{ link.url}} target=_blank>
                                        <i class="fab fa-youtube fa-2x"></i>
                                    </a>
                                {% elif "WE" == link.type_link %}
                                    <a class="sn-link we" href={{ link.url }} target=_blank>
                                        <i class="fas fa-code fa-2x"></i>
                                    </a>
                                {% elif "MA" == link.type_link %}
                                    <a class="sn-link ma" href={{ link.url }} target=_blank>
                                        <i class="fas fa-at fa-2x"></i>
                                    </a>
                                {% else %}
                                    <a class="sn-link ot" href={{ link.url }} target=_blank>
                                        <i class="fas fa-link fa-2x"></i>
                                    </a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if not is_member %}
                        <form method="POST" action="{% url 'associations:join' id=asso.pk  %}">
                            {% csrf_token %}
                            <input class="btn blue darken-2 center" value="join" type="submit"/>
                        </form>
                    {% else %}
                        <a class="btn disabled">Vous êtes déja membre ;)</a>
                    {% endif %}
                </div>
            </div>
            <div id="desc-column">
                <div id="desc-title">
                    <h5>Description</h5>
                </div>
                <div id="desc-description">
                    <p>{{ asso.description }}</p>
                </div>
            </div>
            <div id="event-column">
                <div id="event-title">
                    <h5>Évènements</h5>
                </div>
                <div id="event-description">
                    <p>Ceci est l'endroit où une liste d'événements très intéressants auxquels il faut participer va apparaître</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

eistiens_net_v3/associations/templates/associations/edit.html
{% extends 'common/base.html' %}

{% block title %}{{ name }} - Modification {{ super }}{% endblock %}

{% block content %}
	<h3>Modification - {{ name }}</h3>

	<form action="{% url 'associations:edit' id=pk %}" method="post">
		{{ form.as_p }}
		{% csrf_token %}
		<input class="btn btn-lg green" type="submit" value="Mettre à jour">
	</form>


{% endblock %}

eistiens_net_v3/associations/templates/associations/list.html
{% extends 'common/base.html' %}

{% block title %}Associations {{ super }}{% endblock %}

{% block content %}

	<h3>Toutes les associations</h3>
	<ul class="collection">
	{% for asso, member in assos %}
		<li class="collection-item">
			<a href='{% url 'associations:details' id=asso.pk %}'>{{ asso }}</a>
			{% if member %} (Souscrit) {% endif %}
		</li>
	{% endfor %}
	</ul>

{% endblock %}