eistiens_net_v3/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from accounts import views


urlpatterns = [
    url(r'^login$',  views.login,                     name='login'),
    url(r'^logout$', logout,      {'next_page': '/'}, name='logout'),
]

eistiens_net_v3/associations/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^(?P<id>\d+)$', views.details, name='details'),
    url(r'^(?P<id>\d+)/edit$', views.edit, name='edit'),
    url(r'^join/(?P<id>\d+)$', views.join, name='join'),
]

eistiens_net_v3/eistiens_net_v3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from . import settings
from portal import views as portal_views


urlpatterns = [
    url(r'^$',          portal_views.home_page, name='portal'),
    url(r'^admin/',     admin.site.urls),
    url(r'^accounts/',  include('accounts.urls', namespace='accounts')),
    url(r'^associations/',
        include('associations.urls', namespace='associations')
        ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

eistiens_net_v3/common/models.py
from django.db import models


class SchoolYear(models.Model):
    """
    A model representing a school year. Only one is supposed to be created each
    year, so it can be used to reference everything year-related.
    """
    year = models.PositiveSmallIntegerField()

    def __str__(self):
        return "{}-{}".format(str(self.year), str(self.year + 1))

eistiens_net_v3/common/templates/common/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description" content="Le réseau social étudiant de l'EISTI">
        <meta name="keywords" content="EISTI, Social, Réseau">

       <title>{% block title %}{% endblock title %} | Eistiens.net</title>

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        <link type="text/css" rel="stylesheet" href="{% static "css/normalize.css" %}"/>
        <link type="text/css" rel="stylesheet" href="{% static "css/materialize.min.css" %}"/>
        <link type="text/css" rel="stylesheet" href="{% static "css/styles.css" %}"/>

        {% block css %}{% endblock %}

        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
        <script defer src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    </head>

    <body class="grey lighten-3">

        {% include 'common/navbar.html' %}

        {% if request.user.is_authenticated %}
            {% if messages %}
                {% for message in messages %}
                    {{ message }}<br/>
                    {# TODO: Make better message apparition #}
                {% endfor %}
            {% endif %}
        {% endif %}

        <main>
            <div class="container" style="min-width:100%">
                {% block content %}{% endblock content %}
            </div>
        </main>

        <!-- Piwik -->
        <script type="text/javascript">
            var _paq = _paq || [];
            _paq.push(["setDomains", ["*.eistiens.net","*.www.eistiens.net"]]);
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function() {
                var u="//piwik.atilla.org/";
                _paq.push(['setTrackerUrl', u+'piwik.php']);
                _paq.push(['setSiteId', '4']);
                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
                g.type='text/javascript';
                g.async=true;
                g.defer=true;
                g.src=u+'piwik.js';
                s.parentNode.insertBefore(g,s);
            })();
        </script>
        <noscript>
            <p><img src="//piwik.atilla.org/piwik.php?idsite=4" style="border:0;" alt="" /></p>
        </noscript>
        <!-- End Piwik Code -->
    </body>
</html>

eistiens_net_v3/common/templates/common/navbar.html
{% load static from staticfiles %}

<header>
    <div class="side-nav fixed blue-grey darken-2 white-text">
	<ul>
            {% if request.user.is_authenticated %}
		<li><img src="{% static "img/testImg.png" %}" alt="" class="circle" style="height:10em;padding-left:6.5em;"/></li>
		<li style='text-align:center;' id='username'>{{request.user.username}}</li>
                <li><a id="id_logout" class="center-align" style="padding-left:0;margin-bottom:1em;" href="{% url 'accounts:logout' %}">Déconnexion</a></li>
            {% else %}
                <li><a id="id_login" class="center-align"  style="padding-left:0;margin-bottom:1em;" href="{% url 'accounts:login' %}">Connexion</a></li>
            {% endif %}

                <li><a class="flow-text" href="{% url 'associations:list' %}">Associations</a></li>
                <li><a class="flow-text" href="">Ipsum</a></li>
                <li><a class="flow-text" href="">Dolor</a></li>
                <li><a class="flow-text" href="">Sit Amet</a></li>
        </ul>

        <a href="/" class="blue darken-1 white-text center" style="position:absolute; bottom:0; min-width:100%;min-height:5em; line-height:5em;">
            Eistiens.net
        </a>

    </div>
</header>